name: astumentor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  get_cli: ^1.7.1
  flutter_svg: ^1.0.3
  getwidget: ^2.0.5
  google_fonts: ^2.3.1
  panorama: ^0.4.1
  image_picker: ^0.8.4+11
  shared_preferences: ^2.0.13
  get: 4.6.1
  dio: ^4.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  #to add assets
  assets:
    - assets/images/logos/
    - assets/images/pano/
   

